// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Z-I_9tyK0hKo5juf6z63Gddvj6jXwuM',
    appId: '1:991107430258:web:21178fbb87e79333a58feb',
    messagingSenderId: '991107430258',
    projectId: 'meu-money-f3ab5',
    authDomain: 'meu-money-f3ab5.firebaseapp.com',
    storageBucket: 'meu-money-f3ab5.firebasestorage.app',
    measurementId: 'G-RMH3SWW160',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC4hFQFvGUQh5bYyhiSat6LO_OmxkgeeA',
    appId: '1:991107430258:android:8e892386c6c38721a58feb',
    messagingSenderId: '991107430258',
    projectId: 'meu-money-f3ab5',
    storageBucket: 'meu-money-f3ab5.firebasestorage.app',
  );
}
